export const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "./src/assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "./src/assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./src/assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "./src/assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Thriller",
    category: 1,
    price: 45.0,
    img: "./src/assets/img/5.jpg",
    band: "Michael Jackson",
    year: 1982,
    id: 4,
  },
  {
    title: "A Tábua de Esmeralda",
    category: 4,
    price: 55.0,
    img: "./src/assets/img/6.jpg",
    band: "Jorge Ben Jor",
    year: 1974,
    id: 5,
  },
  {
    title: "As Quatro Estações",
    category: 3,
    price: 40.0,
    img: "./src/assets/img/7.jpg",
    band: "Falamansa",
    year: 2000,
    id: 6,
  },
  {
    title: "Deixa a Vida Me Levar",
    category: 4,
    price: 35.0,
    img: "./src/assets/img/8.jpg",
    band: "Zeca Pagodinho",
    year: 2002,
    id: 7,
  },
  {
    title: "Racionais MC's",
    category: 6,
    price: 30.0,
    img: "./src/assets/img/9.jpg",
    band: "Racionais MC's",
    year: 1994,
    id: 8,
  },
  {
    title: "The Eminem Show",
    category: 7,
    price: 60.0,
    img: "./src/assets/img/10.jpg",
    band: "Eminem",
    year: 2002,
    id: 9,
  },
  {
    title: "Dark Side of the Moon",
    category: 8,
    price: 70.0,
    img: "./src/assets/img/11.jpg",
    band: "Pink Floyd",
    year: 1973,
    id: 10,
  },
  {
    title: "Legend",
    category: 9,
    price: 50.0,
    img: "./src/assets/img/12.jpg",
    band: "Bob Marley",
    year: 1984,
    id: 11,
  },
  {
    title: "Fearless",
    category: 1,
    price: 65.0,
    img: "./src/assets/img/13.jpg",
    band: "Taylor Swift",
    year: 2008,
    id: 12,
  },
  {
    title: "Preciso de Ti",
    category: 11,
    price: 25.0,
    img: "./src/assets/img/14.jpg",
    band: "Diante do Trono",
    year: 2001,
    id: 13,
  },
  {
    title: "Luiz Gonzaga - O Rei do Baião",
    category: 5,
    price: 40.0,
    img: "./src/assets/img/15.jpg",
    band: "Luiz Gonzaga",
    year: 1959,
    id: 14,
  },
  {
    title: "Shania Twain - Come On Over",
    category: 10,
    price: 60.0,
    img: "./src/assets/img/16.jpg",
    band: "Shania Twain",
    year: 1997,
    id: 15,
  }
];


export const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
